### POST request to get acces token regarding authorization code
POST https://app.fakturoid.cz/api/v3/oauth/token
User-Agent: {user-agent}
Content-Type: application/json
Accept: application/json
Authorization: Basic

{
  "grant_type": "authorization_code",
  "code": ,
  "redirect_uri": "https://www.localhost:8080/"
}


### POST request to get access (Bearer) token
POST https://app.fakturoid.cz/api/v3/oauth/token
User-Agent:  {user-agent}
Content-Type: application/json
Accept: application/json
Authorization: Basic

{
  "grant_type": "refresh_token",
  "refresh_token": ""
}


### POST request to refresh access (Bearer) token
POST https://app.fakturoid.cz/api/v3/oauth/token
User-Agent:  {user-agent}
Content-Type: application/json
Accept: application/json
Authorization: {basic-http-auth}

{
  "grant_type": "refresh_token",
  "refresh_token": ""
}

###
